before_script:
  - cd Hash

stages:
  - execute
  - deploy

test:
  stage: execute
  tags:
    - test
  script:
    - composer install --prefer-dist
    - cp .env.testing .env
    - "php artisan doctrine:schema:create"
    - "php artisan doctrine:generate:proxies"
    - vendor/bin/phpunit
  cache:
    key: test
    paths:
      - Hash/vendor
  artifacts:
    paths:
      - Hash/storage/logs/laravel.log
      - Hash/database/database.sqlite

npm:
  stage: execute
  tags:
    - npm
  script:
    - npm install
    - npm run prod
  cache:
    key: npm
    paths:
      - Hash/node_modules
  artifacts:
    paths:
      - Hash/public/css/
      - Hash/public/js/
      - Hash/public/mix-manifest.json

deploy:
  stage: deploy
  when: manual
  tags: 
    - test
  script:
    - cp -rf public $ROOT/projects/AD_2_HashPages/Hash
    - cd $ROOT/projects/AD_2_HashPages/Hash
    - git reset --hard HEAD
    - git pull
    - rm -rf storage/
    - ln -nfs $ROOT/storage storage
    - ln -nfs $ROOT/.env .env
    - composer install --prefer-dist --no-ansi --no-dev --optimize-autoloader
    - "php artisan doctrine:schema:update"
    - "php artisan doctrine:generate:proxies"
    - chgrp apache bootstrap/cache
  dependencies:
    - npm
  environment:
    name: stage
    url: http://proj309-ad-02.misc.iastate.edu/
  variables:
    GIT_STRATEGY: none
    ROOT: /vwh/proj309-ad-02.misc.iastate.edu
  only:
    - master
