before_script:
  - cd Hash

cache:
  paths:
    - Hash/vendor
    - Hash/node_modules

stages:
  - execute
  - deploy

test:
  stage: execute
  tags:
    - test
  script:
    - composer install
    - cp .env.testing .env
    - "php artisan doctrine:schema:create"
    - "php artisan doctrine:generate:proxies"
    - vendor/bin/phpunit

npm:
  stage: execute
  tags:
    - npm
  script:
    - npm install
    - npm run prod
  artifacts:
    paths:
      - Hash/public/css/
      - Hash/public/js/
      - Hash/public/mix-manifest.json

deploy:
  stage: deploy
  when: manual
  tags: 
    - test
  script:
    - cp -r public $ROOT/projects/AD_2_HashPages/Hash/public
    - cd $ROOT/projects/AD_2_HashPages/Hash
    - ln -nfs $ROOT/storage storage
    - ln -nfs $ROOT/.env .env
    - git checkout master
    - git pull
    - rm -rf storage/
    - composer install --prefer-dist --no-ansi --no-dev --optimize-autoloader
    - "php artisan doctrine:schema:update"
    - "php artisan doctrine:generate:proxies"
    - chgrp apache bootstrap/cache
  dependencies:
    - npm
  environment:
    name: stage
    url: http://proj309-ad-02.misc.iastate.edu/
  variables:
    GIT_STRATEGY: none
    ROOT: /vwh/proj309-ad-02.misc.iastate.edu
