before_script:
  - cd Hash

cache:
  paths:
    - Hash/vendor
    - Hash/node_modules

stages:
  - compile
  - deploy

test:
  stage: compile
  tags:
    - shell
  script:
    - composer install
    - vendor/bin/phpunit

build:
  stage: compile
  tags:
    - shell
  script:
    - npm install
    - npm run prod
  artifacts:
    paths:
      - Hash/public/css/
      - Hash/public/js/
      - Hash/public/mix-manifest.json

deploy:
  stage: deploy
  when: manual
  tags: 
    - shell
  script:
    - cp public/* $ROOT/projects/AD_2_HashPages/public
    - cd $ROOT/projects/AD_2_HashPages
    - git pull
    - composer install --prefer-dist --no-ansi --no-dev --optimize-autoloader
    - "php artisan doctrine:schema:update"
    - "php artisan doctrine:generate:proxies"
    - rm -rf storage/
    - ln -nfs $ROOT/storage storage
    - ln -nfs $ROOT/.env .env
    - chgrp apache bootstrap/cache
  dependencies:
    - build
  only:
    - master
  environment:
    name: stage
    url: http://proj309-ad-02.misc.iastate.edu/
  variables:
    GIT_STRATEGY: none
    ROOT: /vwh/proj309-ad-02.misc.iastate.edu
